package n3Excercise1;

public class Persona {

    public Persona () throws ArithmeticException{
        throw new ArithmeticException("Exception lanzada por la clase padre");
    }
}
